book_repo: camelpunch/mybook

sections:
  - repository:
      name: camelpunch/mybook_parts
    directory: part1
  - repository:
      name: camelpunch/mybook_parts
    directory: part2

public_host: mybook.cfapps.io

